name: Release

on:
  release:
    types: [published]

jobs:
  python-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin==0.8.0
          pip install .
      - name: Build Python package
        run: maturin build --release --no-sdist --strip --interpreter python

      - name: List wheels
        if: matrix.os == 'windows-latest'
        run: dir target\wheels\

      - name: List wheels
        if: matrix.os != 'windows-latest'
        run: find ./target/wheels/

      # Note: Windows doesn't support glob
      # https://stackoverflow.com/a/52481267/270334
      - name: Install wheels
        if: matrix.os == 'windows-latest'
        run: pip install --find-links=target\wheels milagro_bls_binding

      - name: Install wheels
        if: matrix.os != 'windows-latest'
        run: pip install target/wheels/milagro_bls_binding*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/wheels/milagro_bls_binding*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PyPi publish
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI }}
        run: maturin publish --no-sdist --username __token__ --interpreter python
